# Stores configuration data

# Site settings
title:            Philosofia
SEOTitle:         Philosofia's Maze
tagline:          A Wanderer 
description:      'I love Brain Dumping'
url:              https://philosofia.github.io/
baseurl:          ""
permalink:        pretty
paginate:         5

plugins:
  - jekyll-gist
  - jekyll-paginate

