# Stores configuration data

# Site settings
title:            Philosofia
SEOTitle:         Philosofia's Maze
tagline:          
description:      'A Wanderer'
url:              
baseurl:          /

# SNS settings


# Build settings
paginate:         5



