# Dependencies
highlighter:      pygments


# Setup
title:            Philosofia
tagline:          
description:      'A Wanderer'
url:              
baseurl:          /

author:
  name:           
  url:            

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://philosofia.github.io/
